name: flutter_ios_android_module
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bot_toast: ^3.0.0
  flutter_screenutil: ^1.0.2
  dio: ^3.0.9
  rflutter_alert: ^1.0.3
  # 下拉刷新
  pull_to_refresh: ^1.6.0
  # 日期选择
  flutter_datetime_picker: ^1.3.8
  # 日期格式化
  date_format: ^1.0.8
  # 自定义 picker
  flutter_picker: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 添加字体
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

  module:
    androidX: true
    androidPackage: com.example.flutter_ios_android_module
    iosBundleIdentifier: com.example.flutterIosAndroidModule
