# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

flutter_application_path = '../flutter_ios_android_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'com_zhaxl' do
  use_frameworks!
  
  # Pods for com_zhaxl
  pod 'Alamofire', '~> 5.1.0'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'SwifterSwift'
  
  # flutter
  install_all_flutter_pods(flutter_application_path)


  target 'com_zhaxlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'com_zhaxlUITests' do
    # Pods for testing
  end

end
