# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

flutter_application_path = '../flutter_ios_android_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'com_zhaxl' do
  use_frameworks!
  
  # Pods for com_zhaxl
  pod 'Alamofire', '~> 5.1.0'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'SwifterSwift'
  # pod 'Nama', '6.7.0' #注意此版本目前为dev版
  # web socket
  pod 'Starscream', '~> 4.0.0'
  pod 'AXWebViewController'
#  pod 'DOAlertController'
  
  # flutter
  install_all_flutter_pods(flutter_application_path)


  target 'com_zhaxlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'com_zhaxlUITests' do
    # Pods for testing
  end

end
